const OK_STATUS = 200;

const CREATED_STATUS = 201;

const BAD_REQUEST_STATUS = 400;

const AUTH_STATUS = 401;

const MISSED_DATA_STATUS = 403;

const NOT_FOUND_STATUS = 404;

const DUPLICATE_STATUS = 409;

const SERVER_ERROR_CODE = 500;

const DATA_DUPLICATION_CODE = 11000;

module.exports = {
  OK_STATUS,
  CREATED_STATUS,
  BAD_REQUEST_STATUS,
  AUTH_STATUS,
  MISSED_DATA_STATUS,
  NOT_FOUND_STATUS,
  DUPLICATE_STATUS,
  SERVER_ERROR_CODE,
  DATA_DUPLICATION_CODE,
};
